### ISSUE TITLE
Add a proper license

### ISSUE THREAD

**Issue by bb010g** [vijithassar/lit#1]
I'd love to use this for work, but the current license is a bit of a barrier. Would you be willing to at least dual license this under [MIT](https://choosealicense.com/licenses/mit/) (or [the Unlicense](https://choosealicense.com/licenses/unlicense/), or [CC0](https://choosealicense.com/licenses/cc0-1.0/))?

**Comment by vijithassar** [comment]
[Done](https://github.com/vijithassar/lit/commit/7feab697c4f0548cfbbaaba09e0d4851dd1efb1b).
